from __future__ import annotations

from typing import Any, Protocol

from workbench.core.domain import CommandSpec, ProviderSpec


class ProviderAdapter(Protocol):
    def spec(self) -> ProviderSpec: ...
    def capabilities(self) -> dict[str, Any]: ...
    def validate(self, config: dict[str, Any]) -> list[str]: ...
    def resolve_config(self, config: dict[str, Any]) -> dict[str, Any]: ...
    def build_command(self, job_kind: str, config: dict[str, Any]) -> CommandSpec: ...
